platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ObjcExtension' do

	pod 'SDWebImage', '~> 4.4.2'

  # Pods for ObjcExtension

  target 'ObjcExtensionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjcExtensionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
