platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ObjcExtension' do

    pod 'ObjcExtension', :path => '../'

  # Pods for ObjcExtensio

  target 'ObjcExtensionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ObjcExtensionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
